#This file is needed for market_places
drbd:
  name: drbd
  predef_name: 
  no_of_instances: 1
  radios: scm_sample
  deps_scm: 
  db_model:
  dbms: 
  link:
  type: SERVICE
  basic_combos: 
  
jenkins:
  name: jenkins
  predef_name: java 
  no_of_instances: 1
  radios: scm_sample
  deps_scm: http://mirrors.jenkins-ci.org/war/latest/jenkins.war
  db_model:
  dbms: 
  link:
  type: SERVICE
  basic_combos:
  
scmmanager:
  name: scmmanager
  predef_name: java 
  no_of_instances: 1
  radios: scm_sample
  deps_scm: https://s3-ap-southeast-1.amazonaws.com/megampub/0.1/war/scmmanager.war
  db_model:
  dbms: 
  link:
  type: SERVICE
  basic_combos:
  
ghost:
  name: ghost
  predef_name: nodejs 
  no_of_instances: 1
  radios: scm_sample
  deps_scm: https://github.com/thomasalrin/ghost.git
  db_model:
  dbms: 
  link:
  type: SERVICE
  basic_combos:
  
wordPress:
  name: wordpress
  predef_name: wordpress
  no_of_instances: 1
  radios: scm_sample
  deps_scm:
  db_model:
  dbms:  
  link:  
  type: SERVICE 
  basic_combos: 

riak:
  name: riak
  no_of_instances: 1
  db_model: full
  dbms: riak
  predef_name:
  radios:
  deps_scm:
  link: http://gomegam.com/docs/users/services/index.html
  type: SERVICE
  basic_combos: riak
    
postgresql:
  name: postgresql
  no_of_instances: 1
  db_model: full
  dbms: postgresql
  predef_name:
  radios:
  deps_scm:    
  link: http://gomegam.com/docs/users/services/index.html
  type: SERVICE
  basic_combos: postgresql
  
sqlite:
  name: sqlite
  no_of_instances: 1
  db_model: full
  dbms: sqlite
  predef_name:
  radios:
  deps_scm:    
  link: http://gomegam.com/docs/users/services/index.html
  type: SERVICE
  basic_combos: sqlite  

redis:
  name: redis
  no_of_instances: 1
  db_model: full
  dbms: redis
  predef_name:
  radios:
  deps_scm:
  link: http://gomegam.com/docs/users/services/index.html
  type: SERVICE
  basic_combos: redis
  
rabbitmq:
  name: rabbitmq
  no_of_instances: 1
  db_model: full
  dbms: rabbitmq
  predef_name:
  radios:
  deps_scm:
  link: http://gomegam.com/docs/users/services/index.html 
  type: SERVICE
  basic_combos: rabbitmq

op5:
  name: op5
  no-of-instances: 1
  radios: scm_sample
  deps_scm:
  db_model:
  dbms:
  predef_name: op5  
  link:   
  type: SERVICE
  basic_combos:

zarafa:
  name: zarafa
  no-of-instances: 1
  radios: scm_sample
  deps_scm:
  db_model:
  dbms:
  predef_name: zarafa 
  link:
  type: SERVICE
  basic_combos:
  
docker:
  name: docker
  no-of-instances: 1
  radios: 
  deps_scm:
  db_model:
  dbms:
  predef_name: docker  
  link: http://gomegam.com/docs/users/index.html  
  type: ADDON
  basic_combos: docker  

byoc:
  name: byoc
  no-of-instances: 1
  radios: 
  deps_scm:
  db_model:
  dbms:
  predef_name: byoc
  link: http://gomegam.com/docs/users/index.html  
  type: BYOC
  basic_combos: byoc  


java:
  name: java
  predef_name: java 
  no_of_instances: 1
  radios: scm_sample
  deps_scm: https://s3-ap-southeast-1.amazonaws.com/megampub/0.1/war/orion.war
  db_model:
  dbms:   
  link: http://gomegam.com/docs/users/apps/index.html
  type: APP 
  basic_combos: java+sqlite
  
rails:
  name: rails
  predef_name: rails 
  no_of_instances: 1
  radios: scm_sample
  deps_scm: https://github.com/thomasalrin/aryabhata.git
  db_model:
  dbms:  
  link: http://gomegam.com/docs/users/apps/index.html
  type: APP
  basic_combos: rails+sqlite
  
play:
  name: play
  predef_name: play 
  no_of_instances: 1
  radios: scm_sample
  deps_scm: https://github.com/thomasalrin/megam_play.git
  db_model:
  dbms:  
  link: http://gomegam.com/docs/users/apps/index.html
  type: APP
  basic_combos: play+riak
  
akka:
  name: akka
  predef_name: akka 
  no_of_instances: 1
  radios: scm_sample
  deps_scm: https://github.com/thomasalrin/megam_akka.git
  db_model:
  dbms:  
  link: http://gomegam.com/docs/users/apps/index.html
  type: APP
  basic_combos: akka+rabbitmq
  
nodejs:
  name: nodejs
  predef_name: nodejs 
  no_of_instances: 1
  radios: scm_sample
  deps_scm: https://github.com/thomasalrin/ghost.git
  db_model:
  dbms:  
  link: http://gomegam.com/docs/users/apps/index.html
  type: APP
  basic_combos: nodejs+sqlite

hadoop:
  name: hadoop
  no_of_instances: 1
  db_model: 
  dbms: 
  predef_name: hadoop
  radios:
  deps_scm:
  link: http://gomegam.com/docs/users/services/index.html
  type: ANALYTICS
  basic_combos: hadoop

