# /var/lib/megam/nilavu.yml
defaults: &defaults
## Specifies the storage used for nilavu's key-value data
##
## Default: riak
##
## Acceptable values:
##   - one of: riak
  storage_backend: riak
## connect.storage.db is a host that the nilavu will connect to
## for saving key/value pairs in storage
## Default: localhost
##
## Acceptable values:
##   - text, e.g. localhost, console.megam.io
  storage: localhost

  ##storage: 103.56.92.13
## enabling/disabling the billing
  billings: on

## Name of the nilavu server
##
## Default: console.megam.io
##
## Acceptable values:
##   - text
  nilavu: https://console.megam.io
## connect.http.api is a host that the nilavu will connect to
## for API  interaction
## Default: api.megam.io
##
## Acceptable values:
##   - text, e.g. localhost, api.megam.io

  http_api: localhost
##http_api: localhost
# Enable log streaming into nilavu
##
## Default: on
##
## Acceptable values:
##   - on or off
  stream_logs: on
## connect.websocket.tap is a host that the nilavu will connect to
## for real time log streaming
## Default: console.megam.io
##
## Acceptable values:
##   - text, e.g. localhost, api.megam.io
  websocket_tap: console.megam.io:7000
## Enable metrics streaming into nilavu
## Requires package [megamanalytics] to be insalled.
## Default: off
##
## Acceptable values:
##   - on or off
  stream_metrics: on
# The metrics source to configure to.
## Default: demo
##
## Acceptable values:
##   - demo, ganglia
  stream_metrics_source: demo
# The metrics source to configure to.
## Default: demo
##
## Acceptable values:
##   - demo, ganglia
  stream_metrics_cluster: megam
## connect.http.metrics is a host that the nilavu will connect to
## for real time metrics streaming
## Default: console.megam.io
##
## Acceptable values:
##   - text, e.g. localhost, api.megam.io
  http_metrics: http://madai.megam.io/monit
# http_gitlabs is a host that the nilavu will connect to
## for pulling data from private repositories
##
## Acceptable values:
##   - text, e.g. http://localhost, api.megam.io
  http_gitlab: http://gitlab.megam.io/api/v3
# billing is the flag to turn on billing/off
## Default: on
##
## Acceptable values:
##   - on or off
  billings: off
# notification section notifies the handlers based on_trigger conditions.
## 1. on_error: When an error occurs then notify dev support via an email to support@megam.io and hipchat. A notification
## via email happens if the configuration for [email:] exists.
## 2. on_some_hap: Turn notification on for notifying when some happenings needs to be notified. (welcome, reset password, balance topup, low credits)
## Default:
##
## Acceptable values:
##   - text
  notification:
    on_some_hap: on
    on_errors: on
    on_info: on
    email:
      id: support@megam.io
      password: <%= ENV["NIL_EMAIL_PASSWORD"] %>
      hipchat:
        api_key: <%= ENV["NIL_HIP_APIKEY"] %>
        room: "Megam"

## Specifies the oauth id/key for various social identities
##
## Default:
##
## Acceptable values:
##   - one of: facebook, github, google
  oauth:
    facebook:
      client_id: <%= ENV["NIL_FB_CLIENT_ID"] %>
      secret_key: <%= ENV["NIL_FB_SECRET_KEY"] %>
    github:
      client_id: <%= ENV["NIL_GIT_CLIENT_ID"] %>
      secret_key: <%= ENV["NIL_GIT_SECRET_KEY"] %>
    google:
      client_id: <%= ENV["NIL_GOO_CLIENT_ID"] %>
      secret_key: <%= ENV["NIL_GOO_SECRET_KEY"] %>

development:
  <<: *defaults

production:
  <<: *defaults
